language: python
python: "3.6"
install:
  - pip install git@github.com:opendreamkit/planetaryum
script:
  - planetaryum
deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
