language: python
python: "3.6"
install:
  - pip install git+https://github.com/OpenDreamKit/planetaryum.git
script:
  - planetaryum
deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
